import { BriefcaseBusiness, FileDown, Sparkles } from 'lucide-react'
import type { IntelligenceReport } from '../types/intelligence'

type Lead={id:string|number;company?:string|null;contact_name?:string|null;status?:string|null}
type Analysis={recommended_service?:string;estimated_value?:number;findings?:string[];opportunities?:string[]}
interface Props{
 money:(value:number)=>string; proposalAnalyses:Record<string|number,Analysis>; intelResult:Analysis|null; intelLead:Lead|null; leads:Lead[]
 proposalLead:Lead|null; setProposalLead:(lead:Lead|null)=>void; setProposalText:(value:string)=>void; setProposalCopied:(value:boolean)=>void
 proposalDefaults:(lead:Lead)=>{service:string;price:string;timeline:string}; proposalService:string; setProposalService:(v:string)=>void
 proposalPrice:string; setProposalPrice:(v:string)=>void; proposalTaxRate:string; setProposalTaxRate:(v:string)=>void; proposalTimeline:string; setProposalTimeline:(v:string)=>void
 proposalText:string; generateProposal:()=>void; proposalTracking:boolean; markProposalSent:()=>void; copyProposal:()=>void; proposalCopied:boolean
 downloadProposalMarkdown:()=>void; printProposal:()=>void; proposalPdfBusy:boolean; proposalOpportunity:IntelligenceReport|null
}

export function ProposalGenerator({money,proposalAnalyses,intelResult,intelLead,leads,proposalLead,setProposalLead,setProposalText,setProposalCopied,proposalDefaults,proposalService,setProposalService,proposalPrice,setProposalPrice,proposalTaxRate,setProposalTaxRate,proposalTimeline,setProposalTimeline,proposalText,generateProposal,proposalTracking,markProposalSent,copyProposal,proposalCopied,downloadProposalMarkdown,printProposal,proposalPdfBusy,proposalOpportunity}:Props){
 const opportunityForLead=proposalOpportunity&&proposalLead?.id===proposalOpportunity.leadId?proposalOpportunity:null
 return <section className="panel proposalPanel" id="proposal"><div className="panelHead"><div><h2>Proposal Generator</h2><p>Turn a lead and its opportunity analysis into a client-ready project proposal.</p></div><span>{opportunityForLead?'Synced from opportunity':'Sales proposal'}</span></div><div className="proposalGrid"><div className="proposalForm">
 <label className="field"><span className="fieldLabel">Choose a lead</span><select value={proposalLead?.id||''} onChange={e=>{const l=leads.find(x=>String(x.id)===e.target.value);setProposalLead(l||null);setProposalText('');setProposalCopied(false);if(l){const d=proposalDefaults(l);setProposalService(d.service);setProposalPrice(d.price);setProposalTimeline(d.timeline)}}}><option value="">Select a prospect…</option>{leads.filter(l=>!['Won','Lost'].includes(l.status||'')).map(l=><option key={l.id} value={l.id}>{l.company} · {l.contact_name||'No contact'}</option>)}</select></label>
 <label className="field"><span className="fieldLabel">Service</span><select value={proposalService} onChange={e=>{const s=e.target.value;setProposalService(s);const p:Record<string,string>={'E-commerce Website':'250000','Website Redesign':'120000','Custom Web Application':'350000','React/MERN Development':'200000','Business Website':'150000'};setProposalPrice(p[s]||'150000');setProposalTimeline(s==='E-commerce Website'?'10–14 business days':s==='Custom Web Application'?'14–21 business days':'7–10 business days')}}><option>Business Website</option><option>E-commerce Website</option><option>Website Redesign</option><option>Custom Web Application</option><option>React/MERN Development</option></select></label>
 <div className="proposalFields"><label className="field"><span className="fieldLabel">Investment (₦)</span><input type="number" value={proposalPrice} onChange={e=>setProposalPrice(e.target.value)}/></label><label className="field"><span className="fieldLabel">Tax rate (%)</span><input type="number" min="0" max="100" step="0.1" value={proposalTaxRate} onChange={e=>setProposalTaxRate(e.target.value)}/></label><label className="field"><span className="fieldLabel">Timeline</span><input value={proposalTimeline} onChange={e=>setProposalTimeline(e.target.value)}/></label></div>
 <div className="proposalFinance"><span>Tax <strong>{money(Number(proposalPrice||0)*Number(proposalTaxRate||0)/100)}</strong></span><span>Total <strong>{money(Number(proposalPrice||0)*(1+Number(proposalTaxRate||0)/100))}</strong></span><span>Milestones <strong>50% / 50%</strong></span></div>
 {opportunityForLead&&<div className="proposalLeadSummary"><strong><Sparkles/> Opportunity synced</strong><span>{opportunityForLead.score}/5 · {opportunityForLead.recommendedService} · {money(opportunityForLead.estimatedValue)}</span><small>{opportunityForLead.keyOpportunities.length} opportunity points loaded into this proposal.</small></div>}
 {proposalLead&&<div className="proposalLeadSummary"><strong>{proposalLead.company}</strong><span>{proposalLead.contact_name||'No contact name'} · {proposalLead.status}</span><small>{proposalAnalyses[proposalLead.id]||(intelResult&&intelLead?.id===proposalLead.id)?'Automated analysis will be included.':'No matching website analysis selected yet.'}</small></div>}
 <div className="intelButtons"><button type="button" className="primary" onClick={generateProposal} disabled={!proposalLead}><BriefcaseBusiness/> Generate Proposal</button><button type="button" className="secondary" onClick={markProposalSent} disabled={!proposalLead||!proposalText||proposalTracking}>{proposalTracking?'Saving…':'Mark Proposal Sent'}</button></div>
 </div><div className="proposalPreview"><div className="reportHead"><div><small>CLIENT-READY DOCUMENT</small><strong>Project Proposal</strong></div><div className="proposalPreviewActions"><button type="button" className="secondary" onClick={copyProposal} disabled={!proposalText}>{proposalCopied?'Copied':'Copy proposal'}</button><button type="button" className="secondary" onClick={downloadProposalMarkdown} disabled={!proposalText}>.md</button><button type="button" className="secondary" onClick={printProposal} disabled={!proposalText||proposalPdfBusy}><FileDown/>{proposalPdfBusy?'Generating…':'Download PDF'}</button></div></div>{proposalText?<pre>{proposalText}</pre>:<div className="intelEmpty"><BriefcaseBusiness/><strong>Your proposal will appear here</strong><span>Select a lead, confirm the service and investment, then generate the proposal.</span></div>}</div></div></section>
}
