import { useEffect, useMemo, useState } from 'react'
import { createClient } from '@supabase/supabase-js'
import { BarChart3, Bell, BriefcaseBusiness, Check, ChevronDown, Filter, LogOut, Plus, RefreshCw, Search, Target, Trash2, Users, X } from 'lucide-react'

const supabase = import.meta.env.VITE_SUPABASE_URL && import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY
  ? createClient(import.meta.env.VITE_SUPABASE_URL, import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY)
  : null

const stages=['New Lead','Contacted','Replied','Interested','Proposal Sent','Won','Lost']
const tone={ 'New Lead':'blue',Contacted:'indigo',Replied:'violet',Interested:'amber','Proposal Sent':'orange',Won:'green',Lost:'red' }
const empty={company:'',contact_name:'',role:'',email:'',phone:'',website:'',instagram:'',niche:'',location:'',source:'Manual',status:'New Lead',deal_value:'',next_follow_up:'',notes:''}
const money=v=>new Intl.NumberFormat('en-NG',{style:'currency',currency:'NGN',maximumFractionDigits:0}).format(Number(v||0))
const today=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}

export default function App(){
 const [session,setSession]=useState(null),[loading,setLoading]=useState(true),[mode,setMode]=useState('login')
 const [email,setEmail]=useState(''),[password,setPassword]=useState(''),[authMsg,setAuthMsg]=useState('')
 const [leads,setLeads]=useState([]),[query,setQuery]=useState(''),[status,setStatus]=useState('All'),[source,setSource]=useState('All')
 const [modal,setModal]=useState(false),[form,setForm]=useState(empty),[saving,setSaving]=useState(false),[syncing,setSyncing]=useState(false),[toast,setToast]=useState('')

 useEffect(()=>{if(!supabase){setLoading(false);return} supabase.auth.getSession().then(({data})=>{setSession(data.session);setLoading(false)});const {data:{subscription}}=supabase.auth.onAuthStateChange((_e,s)=>setSession(s));return()=>subscription.unsubscribe()},[])
 useEffect(()=>{if(session)load()},[session])
 async function load(){const {data,error}=await supabase.from('crm_leads').select('*').order('updated_at',{ascending:false});if(error)notify(error.message);else setLeads(data||[])}
 function notify(x){setToast(x);setTimeout(()=>setToast(''),3000)}
 async function auth(e){e.preventDefault();setAuthMsg('');const r=mode==='login'?await supabase.auth.signInWithPassword({email,password}):await supabase.auth.signUp({email,password});if(r.error)setAuthMsg(r.error.message);else if(mode==='signup')setAuthMsg('Account created. Check your email if confirmation is enabled.')}
 async function signout(){await supabase.auth.signOut();setLeads([])}
 async function syncHubSpot(){setSyncing(true);const r=await supabase.functions.invoke('sync-hubspot',{body:{}});if(r.error)notify(r.error.message||'HubSpot sync failed');else if(!r.data?.success)notify(r.data?.error||'HubSpot sync failed');else{await load();notify(`${r.data.synced} HubSpot deals synchronized`)}setSyncing(false)}
 const filtered=useMemo(()=>{const q=query.toLowerCase().trim();return leads.filter(l=>(!q||[l.company,l.contact_name,l.email,l.niche,l.location,l.source].some(v=>String(v||'').toLowerCase().includes(q)))&&(status==='All'||l.status===status)&&(source==='All'||l.source===source))},[leads,query,status,source])
 const metrics=useMemo(()=>({total:leads.length,active:leads.filter(l=>!['Won','Lost'].includes(l.status)).length,pipeline:leads.filter(l=>!['Won','Lost'].includes(l.status)).reduce((s,l)=>s+Number(l.deal_value||0),0),won:leads.filter(l=>l.status==='Won').reduce((s,l)=>s+Number(l.deal_value||0),0),due:leads.filter(l=>l.next_follow_up&&l.next_follow_up<=today()&&!['Won','Lost'].includes(l.status)).length}),[leads])
 const sources=[...new Set(leads.map(l=>l.source).filter(Boolean))]
 const followUps=useMemo(()=>{const active=leads.filter(l=>l.next_follow_up&&!['Won','Lost'].includes(l.status));const t=today();return {overdue:active.filter(l=>l.next_follow_up<t),today:active.filter(l=>l.next_follow_up===t),upcoming:active.filter(l=>l.next_follow_up>t).sort((a,b)=>a.next_follow_up.localeCompare(b.next_follow_up)).slice(0,5)}},[leads])
 function edit(l){setForm({...l,deal_value:l.deal_value||''});setModal(true)}
 async function save(e){e.preventDefault();setSaving(true);const p={...form,deal_value:form.deal_value?Number(form.deal_value):0,updated_at:new Date().toISOString()};delete p.id;delete p.owner_id;delete p.created_at;const r=form.id?await supabase.from('crm_leads').update(p).eq('id',form.id).select().single():await supabase.from('crm_leads').insert(p).select().single();if(r.error)notify(r.error.message);else{setLeads(x=>form.id?x.map(a=>a.id===r.data.id?r.data:a):[r.data,...x]);setModal(false);notify(form.id?'Lead updated':'Lead added')}setSaving(false)}
 async function remove(id){if(!confirm('Delete this lead?'))return;const r=await supabase.from('crm_leads').delete().eq('id',id);if(r.error)notify(r.error.message);else{setLeads(x=>x.filter(a=>a.id!==id));notify('Lead deleted')}}
 async function move(l,s){const r=await supabase.from('crm_leads').update({status:s,updated_at:new Date().toISOString()}).eq('id',l.id).select().single();if(r.error)notify(r.error.message);else setLeads(x=>x.map(a=>a.id===l.id?r.data:a))}
 if(loading)return <div className="center"><div className="loader"/>Loading Client Engine…</div>
 if(!supabase)return <div className="center"><div className="auth"><b className="logo">JK</b><h1>Client Engine</h1><p>Add the Supabase environment variables to run the app.</p></div></div>
 if(!session)return <div className="center auth-bg"><form className="auth" onSubmit={auth}><b className="logo">JK</b><small>PRIVATE BUSINESS TOOL</small><h1>JohnKay Client Engine</h1><p>One private workspace for leads, follow-ups and deal tracking.</p><label>Email<input type="email" value={email} onChange={e=>setEmail(e.target.value)} required/></label><label>Password<input type="password" value={password} onChange={e=>setPassword(e.target.value)} required minLength="6"/></label>{authMsg&&<em>{authMsg}</em>}<button className="primary wide">{mode==='login'?'Sign in':'Create account'}</button><button type="button" className="link" onClick={()=>setMode(mode==='login'?'signup':'login')}>{mode==='login'?'Create a new account':'Back to sign in'}</button></form></div>
 return <div className="shell"><aside><div className="brand"><b className="logo">JK</b><span><strong>JohnKay</strong><small>Client Engine</small></span></div><nav><button className="active"><BarChart3/>Overview</button><button onClick={()=>document.getElementById('leads').scrollIntoView({behavior:'smooth'})}><Users/>Leads</button><button onClick={()=>{setForm({...empty});setModal(true)}}><Plus/>Add Lead</button></nav><div className="asideBottom"><div className="tip"><Target/>Turn prospects into paying clients.</div><button onClick={signout}><LogOut/>Sign out</button></div></aside>
 <main><header><div><small>PRIVATE WORKSPACE</small><h1>Client acquisition, in one place.</h1><p>Track prospects, follow-ups and potential revenue without rebuilding your workflow every time.</p></div><div className="headerActions"><button className="secondary" onClick={syncHubSpot} disabled={syncing}><RefreshCw className={syncing?"spin":""}/>{syncing?"Syncing…":"Sync HubSpot"}</button><button className="primary" onClick={()=>{setForm({...empty});setModal(true)}}><Plus/>Add lead</button></div></header>
 <section className="metrics"><Metric icon={<Users/>} label="Total leads" value={metrics.total}/><Metric icon={<BriefcaseBusiness/>} label="Active pipeline" value={metrics.active}/><Metric icon={<BarChart3/>} label="Pipeline value" value={money(metrics.pipeline)}/><Metric icon={<Check/>} label="Won value" value={money(metrics.won)}/><Metric icon={<Bell/>} label="Follow-ups due" value={metrics.due}/></section>
 <section className="followups"><div className="panelHead"><div><h2>Follow-up focus</h2><p>Prioritize the prospects that need your attention next.</p></div><span>{followUps.overdue.length+followUps.today.length} need attention</span></div><div className="followupGrid"><FollowupCard title="Overdue" items={followUps.overdue} empty="Nothing overdue" tone="overdue" onEdit={edit}/><FollowupCard title="Due today" items={followUps.today} empty="Nothing due today" tone="today" onEdit={edit}/><FollowupCard title="Upcoming" items={followUps.upcoming} empty="No upcoming follow-ups" tone="upcoming" onEdit={edit}/></div></section>
 <section className="panel" id="leads"><div className="panelHead"><div><h2>Lead pipeline</h2><p>Search and manage prospects from one screen.</p></div><span>{filtered.length} visible</span></div><div className="toolbar"><div className="search"><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search company, person, niche…"/></div><Select icon={<Filter/>} value={status} set={setStatus} options={['All',...stages]}/><Select value={source} set={setSource} options={['All',...sources]}/></div><div className="table"><table><thead><tr><th>Lead</th><th>Stage</th><th>Potential</th><th>Follow-up</th><th>Source</th><th/></tr></thead><tbody>{filtered.map(l=><tr key={l.id}><td><div className="lead"><b>{(l.company||'?')[0]}</b><span><strong>{l.company}</strong><small>{l.contact_name||'No contact name'}{l.niche?' · '+l.niche:''}</small></span></div></td><td><select className={'stage '+tone[l.status]} value={l.status} onChange={e=>move(l,e.target.value)}>{stages.map(s=><option key={s}>{s}</option>)}</select></td><td><strong>{money(l.deal_value)}</strong></td><td className={l.next_follow_up&&l.next_follow_up<=today()&&!['Won','Lost'].includes(l.status)?'due':''}>{l.next_follow_up||'—'}</td><td><span className="pill">{l.source||'Manual'}</span></td><td><div className="actions"><button onClick={()=>edit(l)}>Edit</button><button onClick={()=>remove(l.id)}><Trash2/></button></div></td></tr>)}{!filtered.length&&<tr><td colSpan="6"><div className="empty"><Users/><strong>No leads yet</strong><span>Add your first prospect and start tracking the conversation.</span><button className="primary" onClick={()=>{setForm({...empty});setModal(true)}}><Plus/>Add first lead</button></div></td></tr>}</tbody></table></div></section></main>
 {modal&&<div className="backdrop" onMouseDown={e=>e.target===e.currentTarget&&setModal(false)}><form className="modal" onSubmit={save}><div className="modalHead"><div><small>LEAD RECORD</small><h2>{form.id?'Edit lead':'Add a new lead'}</h2></div><button type="button" onClick={()=>setModal(false)}><X/></button></div><div className="form">{[['company','Company *'],['contact_name','Contact name'],['role','Role'],['email','Email'],['phone','Phone'],['website','Website'],['instagram','Instagram'],['niche','Niche'],['location','Location'],['source','Source'],['deal_value','Potential value (₦)'],['next_follow_up','Next follow-up']].map(([k,l])=><label key={k}>{l}<input type={k==='deal_value'?'number':k==='next_follow_up'?'date':'text'} value={form[k]||''} onChange={e=>setForm({...form,[k]:e.target.value})} required={k==='company'}/></label>)}<label>Stage<select value={form.status} onChange={e=>setForm({...form,status:e.target.value})}>{stages.map(s=><option key={s}>{s}</option>)}</select></label><label className="full">Notes<textarea rows="4" value={form.notes||''} onChange={e=>setForm({...form,notes:e.target.value})}/></label></div><footer><button type="button" onClick={()=>setModal(false)}>Cancel</button><button className="primary" disabled={saving}>{saving?'Saving…':form.id?'Save changes':'Add lead'}</button></footer></form></div>}{toast&&<div className="toast"><Check/>{toast}</div>}</div>
}
function Metric({icon,label,value}){return <div className="metric"><i>{icon}</i><span><small>{label}</small><strong>{value}</strong></span></div>}
function Select({icon,value,set,options}){return <div className="select">{icon}{<select value={value} onChange={e=>set(e.target.value)}>{options.map(x=><option key={x}>{x}</option>)}</select>}<ChevronDown/></div>}
function FollowupCard({title,items,empty,tone,onEdit}){return <div className={'followupCard '+tone}><div className="followupTitle"><strong>{title}</strong><span>{items.length}</span></div>{items.length?items.map(l=><button className="followupItem" key={l.id} onClick={()=>onEdit(l)}><span><b>{l.company}</b><small>{l.contact_name||'No contact name'} · {l.status}</small></span><time>{l.next_follow_up}</time></button>):<div className="followupEmpty">{empty}</div>}</div>}
